name = "duckie-2.0"
main = "src/index.ts"
compatibility_date = "2024-01-01"
[[d1_databases]]
binding = "DB"
database_name = "duckie-db"
[[r2_buckets]]
binding = "R2"
bucket_name = "duckie-assets"
[ai]
binding = "AI"
